// lib/qbank/syllabusKeywords.ts

export type TopicKey =
  | "road-safety"
  | "traffic-signals"
  | "proper-driving"
  | "driving-operations";

export type SubtagKey =
  | "road-safety:license"
  | "road-safety:registration"
  | "road-safety:accidents"
  | "road-safety:road-conditions"
  | "traffic-signals:signal-lights"
  | "traffic-signals:road-signs"
  | "traffic-signals:road-markings"
  | "traffic-signals:police-signals"
  | "proper-driving:safe-driving"
  | "proper-driving:traffic-laws"
  | "driving-operations:indicators"
  | "driving-operations:gears";

export type SubtopicConfig = {
  anchors: readonly string[];   // strong signals (must hit >= 1)
  keywords: readonly string[];  // weaker signals (scoring only)
};

// ✅ only allow subtopic keys that start with the topic prefix
type SubtagKeyFor<T extends TopicKey> = Extract<SubtagKey, `${T}:${string}`>;
// ✅ exact shape of SYLLABUS_RULES: each topic can ONLY have its own subtopics
export type SyllabusRules = {
  [T in TopicKey]: {
    topicAnchors: readonly string[];
    subtopics: Record<SubtagKeyFor<T>, SubtopicConfig>;
  };
};
// NOTE: strings are matched via text.includes(...)
// multi-word phrases must appear in that order.
export const SYLLABUS_RULES = {
  "road-safety": {
    topicAnchors: [
      // license/registration/accidents core
      "driving license",
      "penalty point",
      "probation period",
      "revocation",
      "reissue",
      "replacement",
      "registration",
      "license plate",
      "vehicle license",
      "temporary license plate",
      "motor vehicle inspection",
      "traffic accident",
      "accident scene",
      "report to the police",
      "leave the scene",
      "detain",
      "detaining",
      "procedural regulations",
      "human casulaties",
      "road accident",
      "injured",
      "applicant",
      "admission form",
      "unregistered",
      "test",
      "authorized",
      "qualified driver",
      "years old",
      // “safe driving in various road conditions” (syllabus section 1)
      "fog",
      "foggy",
      "snow",
      "snowy",
      "icy",
      "ice",
      "heavy rain",
      "rainy",
      "night",
      "visibility",
      "tunnel",
      "sharp curve",
      "mountain road",
      "landslide",
      "mudslide",
      "mudflow",
      "muddy",
      "ramp",
      "interchange",
      
      "overtaking",
      "following distance",
      "lane changing",
      "reverse",
      "reversing",
      "uphill",
      "downhill",
      "wet",
      "slippery",
      "muddy",
      "weather",
      "railway",
      "overtake",
      "bridge",
      "situation",
      "conditions",
      "U turn",
      "When encountering",
      "When driving",
      "rainstorm",
      "encounters",
      "overtaking",
      "When a vehicle",
      "flood",
      "road surface",
    ],
    subtopics: {
      "road-safety:license": {
        anchors: ["test", "driving license", "driving licence", "penalty point", "probation period", "revocation"],
        keywords: [
          "application for driving license",
          "validity period",
          "replacement",
          "reissue",
          "physical examination",
          "inspection",
          "pass mark",
          "testing requirements",
        ],
      },
      "road-safety:registration": {
        anchors: ["years old","qualified driver","authorized","unregistered", "applicant", "admission form", "registration", "license plate", "vehicle license", "temporary license plate", "motor vehicle inspection"],
        keywords: ["transfer", "modification", "mortgage", "revocation", "applicant"],
      },
      "road-safety:accidents": {
        anchors: ["accident", "accident scene", "report to the police", "leave the scene", "human casualties", "injured"],
        keywords: ["voluntary negotiation", "expressway", "traffic accident"],
      },
      "road-safety:road-conditions": {
        anchors: [
          "flood",
          "When a vehicle",
          "overtaking",
          "When driving",
          "When encountering",
          "conditions",
          "fog",
          "foggy",
          "snow",
          "snowy",
          "icy",
          "ice",
          "heavy rain",
          "rainy",
          "night",
          "visibility",
          "tunnel",
          "sharp curve",
          "mountain road",
          "landslide",
          "mudslide",
          "mudflow",
          "ramp",
          "interchange",
          "intersection",
          "uphill",
          "downhill",
          "wet",
          "slippery",
          "muddy",
          "weather",
          "railway",
          "overtake",
          "bridge",
          "situation",
          "U turn",
          "rainstorm",
          "encounters",
          "road surface",
          "muddy",
          
        ],
        keywords: [
          "overtaking",
          "following distance",
          "lane changing",
          "reverse",
          "reversing",
          "pedestrian",
          "bicycle",
          "overtake",
          "intersection",
        ],
      },
    },
  },

  "traffic-signals": {
    topicAnchors: [
      "traffic light",
      "red light",
      "green light",
      "yellow light",
      "signal light",
      "arrow shape",
      "signal lights on driving lanes",
      "guide arrow",
      "flashing yellow",
      "level crossing",
      "yellow slash",
      "green arrow",

      "road sign",
      "warning sign",
      "prohibitive",
      "indicative",
      "directional",
      "tourist area",
      "meaning of this sign",
      "meaning of this s ign",
      "This sign",
      "yellow sign",
      "traffic sign",
      "kind of sign",
      "sig n",
      "sign",

      "road marking",
      "markings",
      "marking",
      "mark",
      "yellow line",
      "broken line",
      "solid line",
      "stop line",
      "zebra",
      "line",

      "traffic police",
      "hand signal",
      "hand signals",
      "pull over",
      "slowdown",
      "lane changing",
    ],
    subtopics: {
      "traffic-signals:signal-lights": {
        anchors: [
          "red light", 
          "green light", 
          "yellow light", 
          "signal light", 
          "flashing yellow", 
          "level crossing",
          "traffic light",
          "green arrow",

        ],
        keywords: ["intersection","arrow shape", "signal lights on driving lanes", "level crossing"],
      },
      "traffic-signals:road-signs": {
        anchors: ["road sign", "warning sign", "prohibitive", "indicative", "meaning of this sign", "sig n", "sign", "meaning of this s ign", "This sign", "yellow sign", "traffic sign", "kind of sign"],
        keywords: ["directional", "tourist area"],
      },
      "traffic-signals:road-markings": {
        anchors: [
          "road marking", 
          "markings", 
          "yellow line", 
          "broken line", 
          "solid line", 
          "stop line", 
          "zebra", 
          "crosswalk", 
          "marking", 
          "mark",
          "guide arrow",
          "yellow slash",
          "line",
        ],
        keywords: ["indicative markings", "prohibitive markings", "warning markings", "yellow slash"],
      },
      "traffic-signals:police-signals": {
        anchors: ["traffic police", "hand signal", "hand signals", "pull over", "slowdown"],
        keywords: ["stop signals", "going-straight", "left turn", "right turn", "lane changing"],
      },
    },
  },

  "proper-driving": {
    topicAnchors: [
      // Safe driving content (syllabus section 4)
      "safe driving",
      "safety responsibility",
      "yield",
      "special vehicle",
      "road maintenance",
      "parking",
      "car park",
      "expressway",
      "breakdown",
      "warning requirements",
      "probation",
      "penalty",
      "law",
      "point",
      "drunk",
      "drinking",
      "rest",
      "not safe",
      "safe",

      "How to use lights",
      "pedestrians",
      "max speed",
      "speed up",
      "overtaking",

      "while driving",
      "Which is correct",

      "minimum speed",

      "collision",

      // Traffic laws / penalties (syllabus section 4)
      "prohibited",
      "punishment",
      "drinking",
      "drugs",
      "medicines",
      "illegal driving license",
      "illegal license plate",
      "over-seated",
      "overloaded",
      "cancellation rules",
      "punishment at the scene",
      "violation",
      "illegally",
      "illegal",
      "age",
      "liabilities",
      "subject to",
      "allowed",
    ],
    subtopics: {
      "proper-driving:safe-driving": {
        anchors: ["safe","not safe","rest","overtaking","collision","speed up","minimum speed","Which is correct","while driving","pedestrians","overtake","How to use lights", "safe driving", "safety responsibility", "yield", "special vehicle", "road maintenance", "parking", "expressway", "breakdown"],
        keywords: ["requirements for safe driving", "handling measures", "warning requirements"],
      },
      "proper-driving:traffic-laws": {
        anchors: [
          "subject to",
          "liabilities",
          "age",
          "illegal",
          "drunk",
          "max speed",
          "illegally",
          "point",
          "law",
          "penalty",
          "probation", 
          "violation", 
          "prohibited", 
          "punishment", 
          "drinking", 
          "drugs", "illegal", 
          "over-seated", 
          "overloaded", 
          "cancellation rules",
          "allowed",
        ],
        keywords: ["punishment at the scene", "traffic signal violations", "obtaining driving license by illegal means"],
      },
    },
  },

  "driving-operations": {
    topicAnchors: [
      // instruments/indicators
      "instruments",
      "instrument",
      "indicator",
      "alarm light",
      "fog lamp indicator",
      "engine oil pressure",
      "brake alarm",
      "low fuel warning",
      "water temperature",
      "low-beam",
      "high-beam",
      "seatbelt alarm",
      "flashing hazard light",
      "turn signal",
      "symbol",
      "displays",
      "flashes",
      "lights to indicate",
      "It lights",
      "hazard lights",
      "How to use lights",
      "beam light",

      // controls
      "steering wheel",
      "clutch pedal",
      "brake pedal",
      "accelerator pedal",
      "gear shift",
      "gear shift lever",
      "handbrake",
      "ignition switch",
      "light switch",
      "windscreen wiper",
      "defrost",
      "defog",
      "pedal",
      "switch",
      "safety bags",

      // safety devices (mapped into Indicators by your new taxonomy)
      "safe headrest",
      "seatbelt",
      "seat belt",
      "seat belts",
      "safety",
      "abs",
      "srs",
      "gear",
      "gears",
      "device",
      "devices",
      "tire",
    ],
    subtopics: {
      "driving-operations:indicators": {
        anchors: [
          "indicator",
          "alarm light",
          "engine oil pressure",
          "brake alarm",
          "low fuel warning",
          "water temperature",
          "low-beam",
          "high-beam",
          "seatbelt alarm",
          "flashing hazard light",
          "turn signal",
          "abs",
          "srs",
          "seatbelt",
          "safe headrest",
          "symbol",
          "displays",
          "flashes",
          "lights to indicate",
          "It lights",
          "hazard lights",
          "instrument",
          "How to use lights",
          "beam light",
        ],
        keywords: ["fog lamp indicator", "instruments", "instrument"],
      },
      "driving-operations:gears": {
        anchors: [
          "steering wheel", 
          "clutch pedal", 
          "brake pedal", 
          "accelerator pedal", 
          "gear shift", 
          "handbrake", 
          "ignition switch", 
          "pedal", 
          "switch",
          "seat belts",
          "seat belt",
          "safety",
          "gear",
          "gears",
          "device",
          "devices",
          "tire",
        ],
        keywords: ["light switch", "windscreen wiper", "defrost", "defog","seat belt", "safety bags"],
      },
    },
  },
} as const satisfies SyllabusRules;
